#include <stdio.h>
#include <stdlib.h>

#include "vcutils.h"

int main(){
    /* Type 0 executable.
     * Input: list of strings generated by a tokenizer.
     * Output: list of uint32_t representable integers in base 10.
     * Each line of input generates 1 line of output. */
    unsigned char *phrase = NULL;
    size_t size_phrase = 0;
    ssize_t len_phrase;
    uint32_t hash_result;

    while ((len_phrase = getline((char **)(&phrase), &size_phrase, stdin)) != -1){
        strip_endl(phrase, &len_phrase);

        hash_result = str_hash(phrase, (size_t)(len_phrase));

        printf("%"PRIu32"\n", hash_result);
    }

    free(phrase);

    return 0;
}
